### ISSUE TITLE
CSS专业技巧

### ISSUE THREAD

**Issue by kujian** [kujian/article#7]
原文：https://github.com/AllThingsSmitty/css-protips
译者：[前端开发博客](http://caibaojian.com/) 蔡宝坚
版权：未经许可，禁止转载！

注：翻译进行中，未完

## 使用一个 CSS 重置样式

CSS 重置通过使用一些清晰的样式元素，有利于在不同浏览器之间实现样式的一致性。你可以使用CSS重置库如[Normalize](http://necolas.github.io/normalize.css/)等，或者你可以使用一个更简单的重置方法：

```css
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
```

现在元素将去掉边距和填充，并且```box-sizing```让你可以通过CSS盒子模型来管理布局。

#### [演示](http://codepen.io/AllThingsSmitty/pen/kkrkLL)

**注意**:如果你遵循下面的继承box-sizing技巧，你可以选择不包括box-sizing属性在你的CSS重置中。

## 继承 ```box-sizing```

从```html```开始继承```box-sizing```

```css
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```

这使得它更容易改变插件和其它改变行为组件的```box-sizing```

## 在导航上使用 ```:not``` 来应用或者取消边框

首先是添加边框

```css
/* add border */
.nav li {
  border-right: 1px solid #666;
}
```

然后是去掉最后一个的边框

```css
/* remove border */
.nav li:last-child {
  border-right: none;
}
```

而使用```:not()```伪类只应用在你想要的元素上

```css
.nav li:not(:last-child) {
  border-right: 1px solid #666;
}
```

的确，你可以使用```.nav li + li ```,甚至是```.nav li:first-child ~ li``` ,但使用```:not()```的来定义CSS边框会很清晰并且更加自然。

[演示](http://codepen.io/AllThingsSmitty/pen/LkymvO)

## 在```body```上添加```line-height```

你只需要在```body```上添加```line-height```即可，而不必给每个```<p>```,```<h*>```等添加。

```css
body {
  line-height: 1.5;
}
```
这样子文本元素可以容易从```body```上继承

[演示](http://codepen.io/AllThingsSmitty/pen/VjbdYd)

## 垂直居中一切

不，这不是黑魔法，你真的可以垂直居中元素

```css
html, body {
  height: 100%;
  margin: 0;
}

body {
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
  display: -webkit-flex;
  display: flex;
}
```

想要居中其它的东西？垂直，水平……任何东西，任何时间，任何地点？CSS-Tricks有一篇[写得很好的文章](https://css-tricks.com/centering-css-complete-guide/)解释了这一切。

**注意：** 观察IE11中使用弹性盒(flexbox)的[一些Bug](https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items)

[演示](http://codepen.io/AllThingsSmitty/pen/GqmGqZ)

## 逗号分隔的列表

是列表看起来更像一个真实的逗号分隔列表

```css
ul > li:not(:last-child)::after {
  content: ",";
}
```

使用```:not()```伪类，这样最后一项就不会添加逗号了。

**注意：** 这个技巧对于可访问性（无障碍）可能不是理想的，特别是屏幕阅读器。并且使用CSS生成的内容在浏览器中复制和粘贴是无效的。请保持谨慎。

## 使用负的```nth-child```选择项

在CSS中使用负的 ```nth-child``` 来选择从1到n的项
```css
li {
  display: none;
}

/* select items 1 through 3 and display them */
li:nth-child(-n+3) {
  display: block;
}
```
或者，你也可以尝试一下之前学过的 ```not```：

```css
/* 选择1到3项并显示出来 */
li:not(:nth-child(-n+3)) {
  display: none;
}
```

这是挺简单。

## 使用SVG图标

没有理由不使用SVG图标

```css
.logo {
  background: url("logo.svg");
}
```

SVG在各种分辨率下都有很好的缩放能力，并且支持除了IE9以下的所有浏览器。是时候抛弃你的那些.png,.jpg或者.gif格式的文件了。

**注意:** 如果你只为用户提供SVG图标，并且SVG加载失败，以下样式有助于提升无障碍可访问性。

```css
.no-svg .icon-only:after {
  content: attr(aria-label);
}
```

## 使用“类似猫头鹰”的选择器
它可能有一个奇怪的名字，但使用通用选择(*)和相邻的兄弟选择器(+)能够提供强大的CSS功能：
```css
* + * {
  margin-top: 1.5em;
}
```

## 记单词
enfoce:加强
consistency:一致性
approach:方法
stripped：剥离，去除
intent：意图，目的
separately:分别
textual:文本
Watch for:观察
accessibility:可访问性
Proceed：继续
caution：谨慎
Negative：负的，消极的，否定的
ditch ：抛弃，拍拖
sighted ：有远见的
universal ：普遍，通用
adjacent ：邻
capability：功能，能力
